name: 'CalVer tag'
description: 'Tag a commit with a CalVer version number in the format [YYYY.MM.DD-MICRO]'
author: 'Digital Udvikling'
outputs:
  tag:
    description: 'The generated tag'
runs:
  using: 'node12'
  main: 'dist/index.js'
